name: Build APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes : 60
    env:
      CFLAGS: "-Wno-error=implicit-function-declaration -Wno-error=implicit-int"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Fix Chrome Repo Bug
        run: |
          sudo rm -f /etc/apt/sources.list.d/google-chrome.list
          sudo rm -f /etc/apt/sources.list.d/google-chrome.list.save

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y openjdk-17-jdk python3-pip zip unzip libffi-dev libssl-dev
          pip install --upgrade pip
          pip install "cython==0.29.36" buildozer

      - name: Clean old build
        run: |
          rm -rf .buildozer
          rm -rf bin

      - name: Build APK
        run: |
          yes | buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SweetyMovieApp-APK
          path: bin/*.apk
